on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 */1 * *'
    
jobs:
  sendMessage:
    name: Send Message
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Repo Update
        uses: peter-evans/repository-dispatch@v2
        with:
          event-type: new-release
